### PR TITLE
Fix invalid JSON

### PR DESCRIPTION
**Pull request by vvvv-vvvv**
github-linguist can't parse this file

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I think renaming the file to `.jsonc` would be a better solution than deleting the comments.

**Comment by vvvv-vvvv** [comment]
> I think renaming the file to `.jsonc` would be a better solution than deleting the comments.

Sorry, I should elaborate that this is so I can update github's current ancient atomic-dreams grammar, but the tooling they have is complaining about this file. As for the comments I don't think they really matter anyway

**Comment by SpaceManiac** [comment]
OK, best of luck.

**Comment by vvvv-vvvv** [comment]
They didn't like it because of the GPL code (ofc). Are you fine with making a new repo with just the TM grammar or should I do it myself?

**Comment by SpaceManiac** [comment]
I don't really know what their process is. The `syntaxes/` folder already has its own separate LICENSE. You're welcome to put it in a repo of its own.

**Comment by vvvv-vvvv** [comment]
its now live on github btw

**Pull request merged**
